version: "3.7"

services:
  frontend:
    build:
      context: ./../../../src/frontend/nextjs
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./../../../src/frontend/nextjs:/app
      - nextjs-dev-node_modules:/app/node_modules
      - nextjs-dev-next:/app/.next

  backend:
    build:
      context: ./../../../src/backend/nestjs
      target: development
      dockerfile: Dockerfile
    volumes:
      - ./../../../src/backend/nestjs:/app
    command: yarn run start:debug

  postgres:
    ports:
      - ${DB_PORT}:5432

  pgbouncer:
    ports:
      - ${DB_POOL_PORT}:6432

  sonar:
    ports:
      - ${SONAR_PORT}:9000

  redis:
    ports:
      - ${REDIS_PORT}:6379

volumes:
  nextjs-dev-node_modules:
  nextjs-dev-next:
