version: "3.7"

services:
  backend:
    build:
      context: ./../../../src/backend/nestjs
      target: production
      dockerfile: Dockerfile

  frontend:
    build:
      context: ./../../../src/frontend/nextjs
      target: production
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - /app/.next
