version: "3.7"

services:
  frontend:
    container_name: ${PROJECT_PREFIX}_frontend
    ports:
      - ${FRONTEND_PORT}:3000

  backend:
    container_name: ${PROJECT_PREFIX}_backend
    ports:
      - ${SERVER_PORT}:3000
      - ${DEBUG_SERVER_PORT}:22229
    networks:
      - backend_network
    depends_on:
      - redis
      - pgbouncer

  redis:
    container_name: ${PROJECT_PREFIX}_redis
    image: redis:6.0.8-alpine
    networks:
      - backend_network
    command: redis-server --appendfsync always --requirepass ${REDIS_PASSWORD}
    volumes:
      - redisdata:/data

  postgres:
    container_name: ${PROJECT_PREFIX}_postgres
    image: postgres:12
    networks:
      - backend_network
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgbouncer:
    container_name: ${PROJECT_PREFIX}_pgbouncer
    image: brainsam/pgbouncer:1.7.2
    networks:
      - backend_network
    environment:
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
      DB_NAME: ${DB_DATABASE_NAME}
      DB_HOST: postgres
      MAX_CLIENT_CONN: 10000
    depends_on:
      - postgres

  sonar:
    container_name: ${PROJECT_PREFIX}_sonar
    image: sonarqube

networks:
  backend_network:
volumes:
  pgdata:
  redisdata:
